name: Packaging Test

on: [push, pull_request]

jobs:
  build_qemu:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        # Some asyncio commands require 3.7+
        # It may be possible to use 3.6 and maybe 3.5; however, this will take some patching to get examples to work
        python-version: [3.9]
        qemu-arch: [aarch64,armv7,ppc64le,s390x]

    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.0.10
      name: Run commands
      id: runcmd
      with:
        arch: ${{ matrix.qemu-arch }}
        distro: fedora_latest

        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}

        # Set an output parameter `uname` for use in subsequent steps
        run: |
          echo ::set-output name=uname::$(uname -a)
          dnf -y update
          dnf -y install cmake python${{ matrix.python-version }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py build
          pip install .

    - name: Get the output
      # Echo the `uname` output parameter from the `runcmd` step
      run: |
        echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
