name: Packaging Test

on: [push, pull_request]

jobs:
  build_qemu:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        # Some asyncio commands require 3.7+
        # It may be possible to use 3.6 and maybe 3.5; however, this will take some patching to get examples to work
        python-version: [3.9]
        qemu-arch: [armv7]

    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Run commands
      id: runcmd
      with:
        arch: ${{ matrix.qemu-arch }}
        distro: ubuntu18.04

        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}

        # Set an output parameter `uname` for use in subsequent steps
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)

    - name: Get the output
      # Echo the `uname` output parameter from the `runcmd` step
      run: |
        echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
